Task lesson9
lizakolot12/MyFinances pull request #3
Opened 2023-10-09 12:27 UTC by lizakolot12

Home task for lesson 9

2023-10-09 22:04 UTC, VadymPinchuk requested changes

2023-10-09 22:04 UTC, VadymPinchuk commented on lib/items.dart
> +            child: GridView(
Чи правильно я розумію. У класі з назвою GridItem ми будуємо Widget  у якому Grid є частиною віджета? Це не зовсім правильно якось. Айтем має бути одним із елементі у Грід. А не навпаки

2023-10-09 22:04 UTC, VadymPinchuk commented on lib/items.dart
> +                        )))),
коми перед дужками дуже гарно б виправили форматування

2023-10-09 22:04 UTC, VadymPinchuk commented on lib/main.dart
> +        appBar: AppBar(
порядок елементів дуже зворотній ) якщо дивитись як вони розташтовані на екрані, то це АппБар, Баді, БоттомНавБар. і т д )

2023-10-10 07:47 UTC, lizakolot12 commented on lib/items.dart
> +            child: GridView(
Змінила item для grid.

2023-10-10 07:49 UTC, lizakolot12 commented
Виконала рефакторинг по зауваженням

2023-10-11 10:41 UTC, VadymPinchuk approved these changes

2023-10-11 10:41 UTC, VadymPinchuk commented on lib/items.dart
> +              for (var i in transaction.tags ?? [])
у такому випадку можливо у нас залишиться порожній віджет Wrap якщо у нього не буде чайлдів. Це не критично, але по можливості такого уникати. Зайві віджети це завжди зайве навантаження на UI

2023-10-11 10:41 UTC, VadymPinchuk commented on lib/items.dart
> +                        const EdgeInsets.symmetric(vertical: 4, horizontal: 8),
а кома перед дужкою закриття гарно б вирівняла код ;)

2023-10-11 10:41 UTC, VadymPinchuk commented on lib/items.dart
> +                        borderRadius: BorderRadius.all(Radius.circular(20))),
і тут також )

2023-10-11 10:41 UTC, VadymPinchuk commented on lib/items.dart
> +                    )),
і тут також ) між двома дужками. Це побажання. Але не є помилкою

2023-10-11 10:41 UTC, VadymPinchuk commented on lib/main.dart
> +        appBar: AppBar(
як і писав раніше, якщо є SliverAppBar, to не потрібно використовувати AppBar

2023-10-11 10:41 UTC, VadymPinchuk commented on lib/main.dart
> +    return CustomScrollView(
напевно в такому випадку можна спробувати використати не Слівер. Оскільки у нас лише грід.

2023-10-11 10:41 UTC, VadymPinchuk commented on lib/main.dart
> +  Widget buildStack() {
треба попрацювати над назвами ) щоб було чітко ясно що саме за Стек тут ) або додати документацію

2023-10-12 16:50 UTC, merged