Lesson12
lizakolot12/MyFinances pull request #6
Opened 2023-10-22 17:17 UTC by lizakolot12

2023-10-26 21:38 UTC, VadymPinchuk requested changes

2023-10-26 21:38 UTC, VadymPinchuk commented on lib/lesson12.dart
> +                  title: Row(
ListTile має якраз всі необхідні речі щоб не пхати все в один ряд. tile.leadeing, title, subtitle, trailing

2023-10-26 21:38 UTC, VadymPinchuk commented on lib/lesson12.dart
> +    setState(() {
await repository.removeTask(index)
setState(() {}) 

так було б краще. оскільки в даному випадку взагалі не гарантія що все відбудеться так як потрібно.

2023-10-26 21:38 UTC, VadymPinchuk commented on lib/lesson12.dart
> +    setState(() {
аналогічно

2023-10-27 07:38 UTC, lizakolot12 commented on lib/lesson12.dart
> +                  title: Row(
Використала trailing з ListTile

2023-10-28 22:02 UTC, VadymPinchuk approved these changes

2023-10-28 22:03 UTC, merged