Lesson14
lizakolot12/MyFinances pull request #8
Opened 2023-10-26 18:09 UTC by lizakolot12

Додано provider і riverpod для керування станом.

2023-10-26 21:54 UTC, VadymPinchuk requested changes

2023-10-26 21:54 UTC, VadymPinchuk commented on lib/main.dart
> +    return provider.Consumer<Settings>(builder: (context, settings, child) {
якщо виключно для тесту - міксувати обидва підходи - ок. а взагалі це так дивно бачити обидва варіанти ) не раджу використовувати обидва в релізних додатках, оскільки це може призвести до колізій та нерозуміння флоу

2023-10-26 21:54 UTC, VadymPinchuk commented on lib/list_screen.dart
> +    final repository = ref.watch(repositoryProvider);
радий що не заплуталась у поняттях та зробила все красиво

2023-10-26 21:54 UTC, VadymPinchuk commented on lib/list_screen.dart
> +                  transaction: repository.getAll()[index],
і так не можна )

2023-10-26 21:54 UTC, VadymPinchuk commented on lib/list_screen.dart
> +            childCount: repository.getAll().length,
занадто багато  repository.getAll()

2023-10-26 21:54 UTC, VadymPinchuk commented on lib/data/data.dart
>    List<Transaction> getAll() {
в ідеалі це був би Future<list<Transaction>> і тоді вся архітектура нижче по дереву міняється

2023-10-26 21:54 UTC, VadymPinchuk commented on lib/list_screen.dart
> +                  repository.remove(repository.getAll()[index]);
а ось це не ок ) не можна так. краще винести це у змінну repository.getAll()

2023-10-27 11:18 UTC, lizakolot12 commented on lib/main.dart
> +    return provider.Consumer<Settings>(builder: (context, settings, child) {
Це в якості виконання дз

2023-10-28 22:00 UTC, VadymPinchuk requested changes

2023-10-28 22:00 UTC, VadymPinchuk commented on lib/data/data.dart
> +class TransactionRepository extends ChangeNotifier {
не зовсім правильно. Репозиторій - це лише клас який надає доступ до даних. Але не є Станом. Стан зазвичай може бути ChangeNotifier або ValueNotifier. Репозиторій же потрібно провайдити звичайним Provider<Reposotiry>

2023-10-28 22:00 UTC, VadymPinchuk commented on lib/data/data.dart
> +  Future<void> remove(int index) async {
ось ця частина - мала б належати Стану екрану. і вже з того стану мала б викликати метод repository.remove()

2023-10-31 18:15 UTC, closed without merging